--------------------------------------------------------------------------
-- サンプルデータ投入スクリプト
--------------------------------------------------------------------------

-- 機種マスタ
INSERT INTO MODEL_MASTER (MODEL_ID, MODEL_NAME, MODEL_INFO) VALUES ('M0001', 'ノートPC 14型 A',    'CPU:Core i5 / メモリ:8GB / SSD:256GB');
INSERT INTO MODEL_MASTER (MODEL_ID, MODEL_NAME, MODEL_INFO) VALUES ('M0002', 'ノートPC 15型 B',    'CPU:Core i7 / メモリ:16GB / SSD:512GB');
INSERT INTO MODEL_MASTER (MODEL_ID, MODEL_NAME, MODEL_INFO) VALUES ('M0003', 'デスクトップPC C',   'CPU:Core i5 / メモリ:8GB / SSD:256GB');
INSERT INTO MODEL_MASTER (MODEL_ID, MODEL_NAME, MODEL_INFO) VALUES ('M0004', '液晶ディスプレイ 24型', '解像度:1920x1080 / 非光沢');
INSERT INTO MODEL_MASTER (MODEL_ID, MODEL_NAME, MODEL_INFO) VALUES ('M0005', 'プリンタ複合機 D',   'カラー印刷 / スキャナ機能付き');

-- 取引先マスタ
INSERT INTO CLIENT_MASTER (CLIENT_ID, CLIENT_NAME, CLIENT_CONTACT) VALUES ('C0001', '株式会社サンプル商事',  '03-1111-2222 / sample@example.com');
INSERT INTO CLIENT_MASTER (CLIENT_ID, CLIENT_NAME, CLIENT_CONTACT) VALUES ('C0002', '有限会社テスト工業',    '06-3333-4444 / test@example.com');
INSERT INTO CLIENT_MASTER (CLIENT_ID, CLIENT_NAME, CLIENT_CONTACT) VALUES ('C0003', '株式会社デモシステムズ', '045-5555-6666 / demo@example.com');

-- 従業員マスタ
INSERT INTO EMPLOYEE_MASTER (EMPLOYEE_ID, EMPLOYEE_NAME, HIRE_YEAR, DEPARTMENT) VALUES ('E0001', '山田 太郎', 2018, '営業部');
INSERT INTO EMPLOYEE_MASTER (EMPLOYEE_ID, EMPLOYEE_NAME, HIRE_YEAR, DEPARTMENT) VALUES ('E0002', '鈴木 花子', 2020, '営業部');
INSERT INTO EMPLOYEE_MASTER (EMPLOYEE_ID, EMPLOYEE_NAME, HIRE_YEAR, DEPARTMENT) VALUES ('E0003', '佐藤 次郎', 2022, '倉庫管理部');

-- 在庫テーブル
INSERT INTO INVENTORY (MODEL_ID, QUANTITY) VALUES ('M0001', 50);
INSERT INTO INVENTORY (MODEL_ID, QUANTITY) VALUES ('M0002', 30);
INSERT INTO INVENTORY (MODEL_ID, QUANTITY) VALUES ('M0003', 20);
INSERT INTO INVENTORY (MODEL_ID, QUANTITY) VALUES ('M0004', 15);
INSERT INTO INVENTORY (MODEL_ID, QUANTITY) VALUES ('M0005', 10);

-- 受注管理テーブル
INSERT INTO ORDER_MANAGEMENT (ORDER_ID, CLIENT_ID, ORDER_DATE, MODEL_ID, QUANTITY, DUE_DATE, STATUS, EMPLOYEE_ID)
VALUES ('O00001', 'C0001', DATE '2026-08-01', 'M0001', 5, DATE '2026-08-15', '手配中', 'E0001');

INSERT INTO ORDER_MANAGEMENT (ORDER_ID, CLIENT_ID, ORDER_DATE, MODEL_ID, QUANTITY, DUE_DATE, STATUS, EMPLOYEE_ID)
VALUES ('O00002', 'C0002', DATE '2026-08-05', 'M0002', 3, DATE '2026-08-20', '未処理', 'E0002');

INSERT INTO ORDER_MANAGEMENT (ORDER_ID, CLIENT_ID, ORDER_DATE, MODEL_ID, QUANTITY, DUE_DATE, STATUS, EMPLOYEE_ID)
VALUES ('O00003', 'C0003', DATE '2026-07-20', 'M0004', 10, DATE '2026-08-01', '完了', 'E0001');

COMMIT;
